services:
  frontend:
    build:
      context: .
      dockerfile: docker/vue.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - frontend

networks:
  frontend: